# Generated by Django 3.2.16 on 2023-01-29 16:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('sub', models.CharField(db_index=True, max_length=64, verbose_name='SUB')),
                ('name', models.CharField(default='', max_length=64, verbose_name='이름')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입 날짜')),
                ('last_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='마지막 로그인')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=200, verbose_name='내용')),
            ],
            options={
                'verbose_name': '체크 리스트 목록',
                'verbose_name_plural': '체크 리스트 목록',
                'db_table': 'check_list',
            },
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(editable=False, max_length=20, verbose_name='가입 경로')),
            ],
            options={
                'verbose_name': '가입 경로',
                'verbose_name_plural': '가입 경로',
                'db_table': 'social_platform',
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=200, verbose_name='내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 날짜')),
                ('success', models.BooleanField(default=0, verbose_name='달성 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 목표',
                'verbose_name_plural': '사용자 목표',
                'db_table': 'user_goal',
                'ordering': ['-created_date', 'success'],
            },
        ),
        migrations.CreateModel(
            name='UserCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='선택 날짜')),
                ('value', models.IntegerField(default=0, verbose_name='값')),
                ('check_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.checklist', verbose_name='선택된 질문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 체크리스트',
                'verbose_name_plural': '사용자 체크리스트',
                'db_table': 'user_check',
                'ordering': ['-selected_date'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.socialplatform', verbose_name='가입 경로'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
