# Generated by Django 4.1.5 on 2023-01-31 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consult',
            table=None,
        ),
        migrations.AlterModelTable(
            name='doctor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='goalcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='goallist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='socialplatform',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testlist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usercheck',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usergoal',
            table=None,
        ),
    ]
