# Generated by Django 4.1.5 on 2023-01-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_consult_table_alter_doctor_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consult',
            table='consult',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
        migrations.AlterModelTable(
            name='goalcategory',
            table='goal_category',
        ),
        migrations.AlterModelTable(
            name='goallist',
            table='goal_list',
        ),
        migrations.AlterModelTable(
            name='socialplatform',
            table='social_platform',
        ),
        migrations.AlterModelTable(
            name='testitem',
            table='test_item',
        ),
        migrations.AlterModelTable(
            name='testlist',
            table='test_list',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usercheck',
            table='user_check',
        ),
        migrations.AlterModelTable(
            name='usergoal',
            table='user_goal',
        ),
    ]
